[project]
name = "buffoonbot"
version = "0.1.0"
description = "Playing chess with a tiny brain and a poor memory"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chess>=1.11.1",
    "ruff>=0.9.4",
]
