[project]
name = "buffoonbot"
version = "0.1.0"
description = "Playing chess with a tiny brain and a poor memory"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cairosvg>=2.7.1",
    "chess>=1.11.1",
    "python-chess>=1.999",
    "ruff>=0.9.4",
]
